creatures = [
    {"name": "Ceto", "defeated_by": None},
    {"name": "Typhon", "defeated_by": "Zeus"},
    {"name": "Echidna", "defeated_by": "Argos Panoptes"},
    {"name": "Dino", "defeated_by": None},
    {"name": "Pefredo", "defeated_by": None},
    {"name": "Enyo", "defeated_by": None},
    {"name": "Scylla", "defeated_by": None},
    {"name": "Charybdis", "defeated_by": None},
    {"name": "Euryale", "defeated_by": None},
    {"name": "Stheno", "defeated_by": None},
    {"name": "Medusa", "defeated_by": "Perseus"},
    {"name": "Ladon", "defeated_by": "Heracles"},
    {"name": "Eagle of Caucasus", "defeated_by": None},
    {"name": "Chimera", "defeated_by": "Bellerophon"},
    {"name": "Lernaean Hydra", "defeated_by": "Heracles"},
    {"name": "Nemean Lion", "defeated_by": "Heracles"},
    {"name": "Sphinx", "defeated_by": "Oedipus"},
    {"name": "Colchian Dragon", "defeated_by": None},
    {"name": "Cerberus", "defeated_by": None},
    {"name": "Crommyonian Sow", "defeated_by": "Theseus"},
    {"name": "Orthrus", "defeated_by": "Heracles"},
    {"name": "Cretan Bull", "defeated_by": "Theseus"},
    {"name": "Calydonian Boar", "defeated_by": "Atalanta"},
    {"name": "Carcinus", "defeated_by": None},
    {"name": "Geryon", "defeated_by": "Heracles"},
    {"name": "Clotho", "defeated_by": None},
    {"name": "Lachesis", "defeated_by": None},
    {"name": "Atropos", "defeated_by": None},
    {"name": "Minotaur of Crete", "defeated_by": "Theseus"},
    {"name": "Harpies", "defeated_by": None},
    {"name": "Argus Panoptes", "defeated_by": "Hermes"},
    {"name": "Stymphalian Birds", "defeated_by": None},
    {"name": "Talos", "defeated_by": "Medea"},
    {"name": "Sirens", "defeated_by": None},
    {"name": "Python", "defeated_by": "Apollo"},
    {"name": "Ceryneian Hind", "defeated_by": None},
    {"name": "Basilisk", "defeated_by": None},
    {"name": "Erymanthian Boar", "defeated_by": None}
]
